name: Sobani-build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - v**
  pull_request:
    branches: [ master ]
  release:
    types:
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup Node.js
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0

    # Install yarn and other dev dependencies
    - name: Install yarn and dev dependencies
      run: |
        npm install -g yarn
        yarn install --dev

    # Build dist
    - name: Build dist
      run: yarn dist

    - name: Prepare for uploading dist (linux)
      if: matrix.os == 'ubuntu-18.04'
      run: |
        cd dist
        rm -rf linux-unpacked || true
        AppImage=`ls Sobani-*.AppImage`
        DistFile=${AppImage%AppImage}-linux-x64.AppImage
        mv $AppImage $DistFile

    - name: Prepare for uploading dist (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        cd dist
        rm -f latest-mac.yml || true
        rm -f builder-effective-config.yaml || true
        rm -rf mac || true
        rm -f *.zip || true
        DiskImage=`ls Sobani-*.dmg`
        DistFile=${DiskImage%.dmg}-macos-x64.dmg
        mv $DiskImage $DistFile

    - name: Prepare for uploading dist (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd dist
        rm -r -fo win-unpacked

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Sobani-${{ matrix.os }}
        path: dist/
